version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
      - DBURL=mongodb://sonu:$2b$10$se9ZFsrUzNZ.fGv3HGvmj.GRy6hHq6ie86NCb4EnTj6Wc64FORHX2@mongo:27017/Contact_Management_System
      - CLIENT_URL=http://localhost:3000
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "5173:3000"
    depends_on:
      - backend

  mongo:
    image: mongo:8.14
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongodb:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_DATABASE=Contact_Management_System
      
volumes:
  mongo-data:
